version: '3.8'

services:
  devtrackr:
    build:
      context: .
      dockerfile: Dockerfile
    image: devtrackr
    ports:
      - "8080:8080"
    environment:
      - JIRA_URL=https://issues.redhat.com
      - JIRA_TOKEN=${JIRA_TOKEN:-}
    volumes:
      - ./.devtrackr:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s